shell: create br at script/qemu-ifup file

diff --git a/script/qemu-ifdown b/script/qemu-ifdown
--- a/script/qemu-ifdown
+++ b/script/qemu-ifdown
@@ -1,10 +1,15 @@
 #!/bin/bash
-switch=br0
-if [ -n "$1" ]; then
-	ifconfig ${switch} 2.2.2.1/24 up
-	ip link set $1 down
-	echo "run cmd: [brctl delif $switch $1]"
-	brctl delif ${switch} $1
+TAP=$1
+if [ "X$TAP" == "X" ];then
+	echo "[Error] tap nic is null!!!"
+	exit 1;
+fi
+NUM=$(echo ${TAP} | sed 's/[^0-9]//g')
+switch=br${NUM}
+if [ -n "${TAP}" ]; then
+	ip link set ${TAP} down
+	echo "run cmd: [brctl delif $switch ${TAP}]"
+	brctl delif ${switch} ${TAP}
 
 	ip link set ${switch} down
 	brctl delbr ${switch}
diff --git a/script/qemu-ifup b/script/qemu-ifup
--- a/script/qemu-ifup
+++ b/script/qemu-ifup
@@ -1,10 +1,22 @@
 #!/bin/bash
-switch=br0
-if [ -n "$1" ]; then
-	ifconfig ${switch} 2.2.2.1/24 up
-	ip link set $1 up
-	echo "run cmd: [brctl addif $switch $1]"
-	brctl addif ${switch} $1
+TAP=$1
+echo "tap name=${TAP} argument: $@"
+if [ "X$TAP" == "X" ];then
+	echo "[Error] tap nic is null!!!"
+	exit 1;
+fi
+NUM=$(echo ${TAP} | sed 's/[^0-9]//g')
+switch=br${NUM}
+IPADDR=2.2.${NUM}.1
+if [ -n "${TAP}" ]; then ##tap0
+	ifconfig -a | grep -w ${switch}
+	if [ $? -eq 1 ];then
+		brctl addbr ${switch}
+	fi
+	ifconfig ${switch} ${IPADDR}/24 up
+	ip link set ${TAP} up
+	echo "run cmd: [brctl addif $switch ${TAP}]"
+	brctl addif ${switch} ${TAP}
 	exit 0
 else
 	echo "Error: no interface specified!!!!"
